### PR TITLE
Loyal challenger bug

### PR DESCRIPTION
**Pull request by Matthew-Griffith**
tests for issue #3040

### CODE REVIEW

**Comment by Matthew-Griffith** [comment]
I just realized the test is wrong the first player gains two off the air ring. I'll fix it in the morning

**Comment by jamesoddy** [comment]
@Matthew-Griffith I've created a PR to your branch which has a test which I suspect was the problem and a fix.

**Comment by jamesoddy** [comment]
Sorry, I should have explained further.  Loyal Challenger was looking at `context.player` rather than `context.source.controller`, which I suspect (not 100% sure) will be the player than first plays Loyal Challenger - your tests are passing because Loyal Challenger was already in the discard.  The new test gets player1 to play Loyal Challenger first, then assasinated and then Shosuro Actress takes control.  That fails unless we change to `context.source.controller`.

**Comment by Matthew-Griffith** [comment]
that's great I just wrote the test off the issue reported by a player and it didn't have a screen shot. so I just wrote a basic test and saw it was passing and did pay it a ton of attention.

**Pull request merged**
