### PR TITLE
Henshin Disciple

### LINKED ISSUE #1249: Henshin Disciple
image

### PR DESCRIPTION
**Pull request by CDMayberry**
Closes #1249

### CODE REVIEW

**Comment by CDMayberry** [comment]
A small set of tokens to signify the disciple is getting a boost might be helpful eventually. I forgot I had ring of fire claimed during a test, and was briefly confused when my second disciple won a conflict and got honored. I don't think it warrants doing now, but after the 6x6 is over it might be something I look into.

**Comment by gabilshar** [comment]
hi! the ability still does not trigger

thx!

**Comment by CDMayberry** [comment]
@gabilshar can you make a new issue in the issues tab, and add more detail about the game? Game state, attacking, what ring, etc?

**Comment by gabilshar** [comment]
done :-)

**Pull request merged**
