### PR TITLE
Implementing Hiruma Skirmisher

### LINKED ISSUE #1077: Hiruma Skirmisher
image

### PR DESCRIPTION
**Pull request by SnarkAttack**
Closes #1077

### CODE REVIEW

**Comment by jeremylarner** [comment]
It occurs to me that you may not have tested it because api data for this card isn't available from 5rdb.  I'd recommend changing the id to match another card that is in the database, and testing it that way.

**Comment by SnarkAttack** [comment]
I tested it last night, the data for Hiruma Skirmisher is available

**Comment by jeremylarner** [comment]
And it worked, with that code?  Because I can't see how that effect will grant Skirmisher (or anyone else) Covert...

**Comment by SnarkAttack** [comment]
So it did work even with the match, since the only target was itself (you just picked it). But you're right, not having the match is probably the cleaner way. Updated in the most recent commit.

**Comment by SnarkAttack** [comment]
Updated again. I apologize for not catching this when I tested.

**Pull request merged**
