### PR TITLE
Bugfix - Shinjo Tatsuo to target himself correctly

### PR DESCRIPTION
**Pull request by jamesoddy**
Includes tests

### CODE REVIEW

**Comment by jeremylarner** [comment]
Hmmm, this matches the card, but is it the way we want to go in terms of UI?  I'm wondering if a better fix is just to add `condition: context => !context.source.isParticipating()`

**Comment by jamesoddy** [comment]
I'm thinking Hantei - doesn't it need to "target" for him to be able to override?

**Comment by jamesoddy** [comment]
Ah looks like I need to check some other tests as well.  I'll take a look at them.

**Comment by jeremylarner** [comment]
On second thoughts, I think your fix here is the best way to do it

**Pull request merged**
