### PR TITLE
Backhanded Compliment

### PR DESCRIPTION
**Pull request by CDMayberry**
I got this working, though I see a lot of places uses promptWithHandlerMenu rather than target -> select. Would it be better to re-write it to use that instead?

Implements #1163

### CODE REVIEW

**Comment by jeremylarner** [comment]
I'm pretty sure this works but it needs test fixes, and I'm not sure it's the best way to do it from a UI point-of-view.  I think a better approach might be to make the select prompt between 'Me' and 'My Opponent'.

If you want to go with player names, you need to add 'getPlayers' to the jasmine game object in the failing test.  If you're not sure how to do that, I can submit a PR to your branch for it.

**Comment by CDMayberry** [comment]
I agree from a UI perspective it would be best to do Me/My Opponent, though I did like that this worked with N players. I'll go ahead and swap to the Me/My Opponent, I'll rewrite the test if it's still needed after I rework this.

**Comment by CDMayberry** [comment]
No, your completely right, I just forgot how choices worked.

**Comment by CDMayberry** [comment]
Updated and tested.

**Pull request merged**
