### PR TITLE
Modify the game UI to fit on a 1366x768 laptop

### PR DESCRIPTION
**Pull request by devofdisaster**
Related to #474 .
Split all the changes into commits to make it easier to CR. 
This still requires the player to have card size set to at most normal, the bigger settings just make the cards too large to realistically fit within the current game board layout.

Changes made:

- Split the stylesheets across multiple files
- A bunch of resizing for menus, navbars and whathaveyous
- Dynasty decks are no longer displayed after both players confirm their stronghold province choice
- The draggable prompt window and hand are positioned in the center of the screen by default
- Chat was rewritten into a separate component, and is now toggleable, while the gameboard stretches to the right edge of the screen
- Chat shows a notification icon if it's collapsed and messages are received from the other player 
- Added an option in profile settings to collapse the player status bars into the ring sidebar, saving vertical space on smaller screens
- Added a button for toggling the manual mode on and off

### CODE REVIEW

**Comment by devofdisaster** [comment]
After latest commits:

screen shot 2017-11-19 at 09 39 24

screen shot 2017-11-19 at 09 44 25

**Comment by gryffon** [comment]
I have some additional thoughts on this, maybe you might be able to help with those.

What if we put the chat and/or rings on a tab(like the user list in the lobby) or just hide it and use a ctrl-key sequence to toggle the visibility?

That way, some of the elements that are not in constant use could be optional and/or viewed when needed. Even better if those elements can float on top when visible.

**Comment by devofdisaster** [comment]
With the above changes:

screen shot 2017-11-22 at 14 24 56

screen shot 2017-11-22 at 14 11 26

**Comment by gryffon** [comment]
Can you add an updated screenshot?

Also we talked about being able to switch between a status block and a status bar, did we decide to put that in a future change? (Just trying to refresh myself).

**Comment by devofdisaster** [comment]
Yeah, the bar/block switchamajig is in here, as a checkbox in player profile/game settings, as well as chat show/collapse button with notifications and a manual mode button.

screen shot 2017-11-27 at 19 00 37

screen shot 2017-11-27 at 19 00 49

screen shot 2017-11-27 at 19 04 46

screen shot 2017-11-27 at 19 01 12

screen shot 2017-11-27 at 19 01 06

screen shot 2017-11-27 at 19 14 35

**Pull request merged**
