### PR TITLE
My current development branch

### PR DESCRIPTION
**Pull request by jeremylarner**
This branch has most of the framework steps implemented.  I'm still debugging it, but it's somewhat stable if you want to take a look.

Any comments/suggestions gratefully received!

### CODE REVIEW

**Comment by elstob** [comment]
May I recommend in future that you keep your pull requests to a single specific feature each time instead of as a giant branch of changes like this? That will make it a lot easier for @gryffon to review the changes and track down any bugs or issues that might arise from a merge. It will mean a little more admin on your end but makes life infinitely easier for your collaborators.

**Comment by jeremylarner** [comment]
I appreciate that it's difficult to spot bugs with so many changes.  I'll try and break my changes down into individual features and make a separate PR for each.

**Comment by jeremylarner** [comment]
I've submitted PRs for (what I think are) the least controversial of my changes.  I have another 7 or 8 features split out from this codebase, but they often depend on the submitted changes, so I'll submit them once the other ones have been merged.

**Comment by gryffon** [comment]
Closing this, as it's been separated into multiple smaller PRs.

**Pull request closed without merging**
